<a href="https://colab.research.google.com/github/rladnrgus/2024-1-my-BDA/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EA%B3%BC%EC%A0%9C_09%EC%A1%B0_20231597_%EC%B5%9C%EC%A7%80%EC%95%88_20231598_%EA%B9%80%EC%9A%B1%ED%98%84_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import site
site.getsitepackages()

['/usr/local/lib/python3.10/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3.10/dist-packages']

In [ ]:
!pip install koreanize_matplotlib

Collecting koreanize_matplotlib
  Downloading koreanize_matplotlib-0.1.1-py3-none-any.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 50.9 MB/s eta 0:00:00
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from koreanize_matplotlib) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize_matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize_matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize_matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize_matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize_matplotlib) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize_matplotlib) (24.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize_matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize_matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize_matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->koreanize_matplotlib) (1.16.0)
Installing collected packages: koreanize_matplotlib
Successfully installed koreanize_matplotlib-0.1.1

# **1.데이터 불러오기**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
df = pd.read_csv('서울시 지하철 호선 별 역별 시간대별 승하차 인원정보.csv') #pd.read_csv를 사용하여 datafream형태로 읽어오기

In [ ]:
df=df.transpose()
df

,0,1,2,3,4,5,6,7,8,9,...,66197,66198,66199,66200,66201,66202,66203,66204,66205,66206
사용월,202404,202404,202404,202404,202404,202404,202404,202404,202404,202404,...,201501,201501,201501,201501,201501,201501,201501,201501,201501,201501
호선명,1호선,1호선,1호선,1호선,1호선,1호선,1호선,1호선,1호선,1호선,...,중앙선,중앙선,중앙선,중앙선,중앙선,중앙선,중앙선,중앙선,중앙선,중앙선
지하철역,동대문,동묘앞,서울역,시청,신설동,제기동,종각,종로3가,종로5가,청량리(서울시립대입구),...,양원,양정,양평,오빈,용문,운길산,원덕,중랑,팔당,회기
04시-05시 승차인원,708,231,658,94,371,409,140,213,38,1145,...,18,8,9,0,134,0,1,14,0,436
04시-05시 하차인원,7,1,24,2,25,2,4,9,2,21,...,0,0,0,0,1,0,0,1,0,3
05시-06시 승차인원,11309,3091,8560,2321,8785,5326,3754,3993,1997,11873,...,1401,333,1625,227,702,177,292,4929,161,10929
05시-06시 하차인원,2206,802,9158,5550,2166,2524,5916,2632,3764,2610,...,149,145,52,5,5,56,4,424,50,3067
06시-07시 승차인원,9917,4051,14541,4123,10319,9582,4432,3760,3361,19144,...,2084,625,2169,296,1769,642,415,8539,368,23317
06시-07시 하차인원,7632,5422,62765,26788,9477,10009,31983,13113,17380,10607,...,1692,482,1317,123,488,403,46,2084,149,10430
07시-08시 승차인원,16477,9024,43682,7965,22808,22601,6987,6192,5936,50516,...,5683,2245,11361,870,4636,1292,537,22160,1227,65043
07시-08시 하차인원,13074,10925,121498,76757,27491,21872,116830,28333,43604,18457,...,2243,1632,2903,309,1337,675,248,3027,523,24473
08시-09시 승차인원,21936,13810,75625,11415,33089,33720,11438,10487,10505,60787,...,5618,1662,6769,897,4919,1479,823,25792,910,85473
08시-09시 하차인원,20928,23413,247481,204838,58404,40499,271585,69582,99401,40667,...,6092,3180,6391,500,3288,1390,344,6573,1151,59383
09시-10시 승차인원,20056,12127,69569,13882,22394,24375,13857,14903,15190,38368,...,3543,1328,7187,928,4760,1438,980,14328,897,54247
09시-10시 하차인원,24411,18098,165780,94008,33115,34844,153462,67013,67784,40203,...,2674,1268,5783,275,2910,3270,273,6133,2931,41911
10시-11시 승차인원,17984,13323,64964,16811,19633,25928,19090,21481,24499,34032,...,3064,1259,7124,859,6115,1408,1025,11117,1009,42703
10시-11시 하차인원,26080,24169,89882,50246,21299,39135,65403,56758,60892,40921,...,3185,940,6275,409,5386,3673,497,5605,3932,35003
11시-12시 승차인원,19424,17932,83579,22260,20937,32789,28559,32378,36685,38628,...,2961,1100,7385,691,4379,1179,720,10340,904,44815
11시-12시 하차인원,28829,32263,79071,45931,18479,44605,58646,66230,62864,47043,...,2388,912,6933,385,8856,3090,504,5192,2199,33229
12시-13시 승차인원,23661,25352,92596,23951,22666,38939,34028,41670,45987,45870,...,4358,1152,7980,603,6464,1268,571,10853,1086,49662
12시-13시 하차인원,27339,35723,85488,41705,19302,45521,51264,66793,58683,49631,...,2330,705,7721,340,11208,1780,537,6016,1333,40029
13시-14시 승차인원,25539,34346,91583,32711,25010,41805,43174,49408,53569,46739,...,3706,1309,8675,580,7246,2081,684,10510,1371,50237
13시-14시 하차인원,25852,40053,85617,41118,20300,47710,50404,61232,54562,52309,...,2790,879,7092,489,7415,2147,390,7633,897,43452
14시-15시 승차인원,26724,35911,77942,40644,23677,44780,54045,58537,62163,49048,...,2854,1317,7992,474,10503,3065,537,9260,1944,47849
14시-15시 하차인원,24170,33623,77821,32395,18717,45354,41831,52853,50877,50923,...,2583,907,6034,417,7601,1559,513,8331,929,44550
15시-16시 승차인원,28215,36307,107061,55315,25136,46888,66388,67386,65474,53901,...,3257,1486,7767,917,12154,4009,650,8473,2514,51288
15시-16시 하차인원,22128,28454,80047,28761,20530,38738,36375,45645,42509,48118,...,2787,1001,8308,600,6703,1355,683,10252,996,44759
16시-17시 승차인원,28513,38012,121232,63996,29458,46321,81012,74639,71618,57879,...,2943,1477,8354,532,8412,3782,557,8259,2357,53521
16시-17시 하차인원,22183,22028,85791,27301,22012,34891,38714,43708,39876,47234,...,3284,1072,6006,643,5635,1432,731,12166,960,46582
17시-18시 승차인원,26641,35079,186861,98807,42658,44241,153426,88068,88592,53603,...,3567,2338,7221,520,5282,3571,481,8279,2260,62104
17시-18시 하차인원,21646,16605,97810,28303,24664,29528,45018,42730,35214,48901,...,3199,970,7789,547,4964,1300,735,13786,979,59257
18시-19시 승차인원,24483,24960,232292,164218,52889,40379,220336,97536,97906,47248,...,2814,3004,6565,355,4337,2304,563,8399,1617,59218
18시-19시 하차인원,22954,13666,97360,26671,31891,28866,48477,43348,31830,58923,...,4337,1410,9892,996,5347,1218,721,19547,822,76039
19시-20시 승차인원,17860,12144,127623,65574,21913,22224,97736,60598,51431,27366,...,1348,1365,3592,146,2184,1332,175,6449,845,38996
19시-20시 하차인원,22069,9578,68217,13940,23357,19162,25030,23791,19468,38355,...,4264,1460,6130,562,4768,1457,714,21424,749,81870
20시-21시 승차인원,15711,6961,88686,58650,15004,14668,83719,51089,37599,21866,...,1158,663,3540,131,1408,1002,156,4652,492,33754
20시-21시 하차인원,15447,6903,49834,10320,16160,12665,13279,13529,11041,24365,...,2865,866,7356,633,3568,769,612,14362,320,53481
21시-22시 승차인원,14206,6009,89528,51328,14481,9528,86190,53532,33165,16697,...,903,466,2713,109,778,942,53,3849,420,34364
21시-22시 하차인원,13947,7077,45770,8905,16241,11819,10047,10456,7925,23174,...,2110,773,4077,544,2332,760,404,11678,319,50706
22시-23시 승차인원,10894,4180,60579,32067,9660,5984,61700,42546,21398,10841,...,638,249,2250,51,553,270,71,3062,309,31606
22시-23시 하차인원,13041,7442,30821,6293,14335,9885,7354,8327,5978,19857,...,2512,667,5534,480,2496,775,339,11060,339,49658
23시-24시 승차인원,5546,1303,28952,10700,4282,2574,27596,19796,6494,4394,...,201,103,772,32,184,111,8,1619,107,18205
23시-24시 하차인원,9476,4900,14443,4110,9376,6027,4706,5417,3795,12367,...,1587,550,3691,416,1462,633,383,6501,336,35702
00시-01시 승차인원,693,151,3203,661,423,211,2029,2108,366,364,...,44,10,163,3,2,3,3,86,8,767
00시-01시 하차인원,3153,2459,3771,1172,3048,1665,1395,2426,1319,4043,...,339,231,1711,150,1338,222,157,1617,85,9314
01시-02시 승차인원,0,2,3,3,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
01시-02시 하차인원,266,322,263,40,0,0,2,38,0,0,...,0,0,0,0,0,0,0,0,0,0
02시-03시 승차인원,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
02시-03시 하차인원,0,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
03시-04시 승차인원,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
03시-04시 하차인원,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
작업일자,20240503,20240503,20240503,20240503,20240503,20240503,20240503,20240503,20240503,20240503,...,20151223,20151223,20151223,20151223,20151223,20151223,20151223,20151223,20151223,20151223

In [ ]:
subway #데이터 출력

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
0,202404,1호선,동대문,708,7,11309,2206,9917,7632,16477,...,9476,693,3153,0,266,0,0,0,0,20240503
1,202404,1호선,동묘앞,231,1,3091,802,4051,5422,9024,...,4900,151,2459,2,322,0,0,0,0,20240503
2,202404,1호선,서울역,658,24,8560,9158,14541,62765,43682,...,14443,3203,3771,3,263,0,0,0,0,20240503
3,202404,1호선,시청,94,2,2321,5550,4123,26788,7965,...,4110,661,1172,3,40,1,0,0,0,20240503
4,202404,1호선,신설동,371,25,8785,2166,10319,9477,22808,...,9376,423,3048,0,0,0,0,0,0,20240503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66202,201501,중앙선,운길산,0,0,177,56,642,403,1292,...,633,3,222,0,0,0,0,0,0,20151223
66203,201501,중앙선,원덕,1,0,292,4,415,46,537,...,383,3,157,0,0,0,0,0,0,20151223
66204,201501,중앙선,중랑,14,1,4929,424,8539,2084,22160,...,6501,86,1617,0,0,0,0,0,0,20151223
66205,201501,중앙선,팔당,0,0,161,50,368,149,1227,...,336,8,85,0,0,0,0,0,0,20151223
66206,201501,중앙선,회기,436,3,10929,3067,23317,10430,65043,...,35702,767,9314,0,0,0,0,0,0,20151223

In [ ]:
print(subway.head()) #상위 5개 데이터 출력

      사용월  호선명 지하철역  04시-05시 승차인원  04시-05시 하차인원  05시-06시 승차인원  05시-06시 하차인원  \
0  202404  1호선  동대문           708             7         11309          2206
1  202404  1호선  동묘앞           231             1          3091           802
2  202404  1호선  서울역           658            24          8560          9158
3  202404  1호선   시청            94             2          2321          5550
4  202404  1호선  신설동           371            25          8785          2166

   06시-07시 승차인원  06시-07시 하차인원  07시-08시 승차인원  ...  23시-24시 하차인원  00시-01시 승차인원  \
0          9917          7632         16477  ...          9476           693
1          4051          5422          9024  ...          4900           151
2         14541         62765         43682  ...         14443          3203
3          4123         26788          7965  ...          4110           661
4         10319          9477         22808  ...          9376           423

   00시-01시 하차인원  01시-02시 승차인원  01시-02시 하차인원  02시-03시 승차인원  02시-03시 하차인원  \
0          3153             0           266             0             0
1          2459             2           322             0             0
2          3771             3           263             0             0
3          1172             3            40             1             0
4          3048             0             0             0             0

   03시-04시 승차인원  03시-04시 하차인원      작업일자
0             0             0  20240503
1             0             0  20240503
2             0             0  20240503
3             0             0  20240503
4             0             0  20240503

[5 rows x 52 columns]

In [ ]:
subway.info() # 데이터 정보 요약

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66207 entries, 0 to 66206
Data columns (total 52 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   사용월           66207 non-null  int64
 1   호선명           66207 non-null  object
 2   지하철역          66207 non-null  object
 3   04시-05시 승차인원  66207 non-null  int64
 4   04시-05시 하차인원  66207 non-null  int64
 5   05시-06시 승차인원  66207 non-null  int64
 6   05시-06시 하차인원  66207 non-null  int64
 7   06시-07시 승차인원  66207 non-null  int64
 8   06시-07시 하차인원  66207 non-null  int64
 9   07시-08시 승차인원  66207 non-null  int64
 10  07시-08시 하차인원  66207 non-null  int64
 11  08시-09시 승차인원  66207 non-null  int64
 12  08시-09시 하차인원  66207 non-null  int64
 13  09시-10시 승차인원  66207 non-null  int64
 14  09시-10시 하차인원  66207 non-null  int64
 15  10시-11시 승차인원  66207 non-null  int64
 16  10시-11시 하차인원  66207 non-null  int64
 17  11시-12시 승차인원  66207 non-null  int64
 18  11시-12시 하차인원  66207 non-null  int64
 19  12시-13시 승차인원  66207 non-null  int64
 20  12시-13시 하차인원  66207 non-null  int64
 21  13시-14시 승차인원  66207 non-null  int64
 22  13시-14시 하차인원  66207 non-null  int64
 23  14시-15시 승차인원  66207 non-null  int64
 24  14시-15시 하차인원  66207 non-null  int64
 25  15시-16시 승차인원  66207 non-null  int64
 26  15시-16시 하차인원  66207 non-null  int64
 27  16시-17시 승차인원  66207 non-null  int64
 28  16시-17시 하차인원  66207 non-null  int64
 29  17시-18시 승차인원  66207 non-null  int64
 30  17시-18시 하차인원  66207 non-null  int64
 31  18시-19시 승차인원  66207 non-null  int64
 32  18시-19시 하차인원  66207 non-null  int64
 33  19시-20시 승차인원  66207 non-null  int64
 34  19시-20시 하차인원  66207 non-null  int64
 35  20시-21시 승차인원  66207 non-null  int64
 36  20시-21시 하차인원  66207 non-null  int64
 37  21시-22시 승차인원  66207 non-null  int64
 38  21시-22시 하차인원  66207 non-null  int64
 39  22시-23시 승차인원  66207 non-null  int64
 40  22시-23시 하차인원  66207 non-null  int64
 41  23시-24시 승차인원  66207 non-null  int64
 42  23시-24시 하차인원  66207 non-null  int64
 43  00시-01시 승차인원  66207 non-null  int64
 44  00시-01시 하차인원  66207 non-null  int64
 45  01시-02시 승차인원  66207 non-null  int64
 46  01시-02시 하차인원  66207 non-null  int64
 47  02시-03시 승차인원  66207 non-null  int64
 48  02시-03시 하차인원  66207 non-null  int64
 49  03시-04시 승차인원  66207 non-null  int64
 50  03시-04시 하차인원  66207 non-null  int64
 51  작업일자          66207 non-null  int64
dtypes: int64(50), object(2)
memory usage: 26.3+ MB

In [ ]:
sns.get_dataset_names

In [ ]:
sns.load_dataset('iris')

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## **2. 데이터 정제**

**2.1 비어있는 column 지우기**

In [ ]:
#subway_del = subway.drop(column = ['',''])# 데이터를 요약할 것이 없기 때문에 안지웠다. Incheon_del = Incheon.drop(columns = ['',''])

In [ ]:
#subway_del.info() #column을 확인

NameError: name 'subway_del' is not defined

In [ ]:
# data read
address_subway = pd.read_csv('서울시 지하철 호선 별 역별 시간대별 승하차 인원정보.csv',encoding='')

# 호선명이랑 지하철 역 정보만 추출
address_subway=address_subway.loc[address_subway['사용월']==202105,:]
address_subway=address_subway[['호선명','지하철역']]

In [ ]:
# 정확한 위도와 경도를 얻기위해 역 추가
for i in address_station.index:
    station=''.join(list(address_station.loc[i,['지하철역']]))
    if station[-1] != '역':
        address_station.loc[i,['지하철역']] = station+'역's